### ISSUE TITLE
At the time of execuiting my scripts I am getting following error

### ISSUE THREAD

**Issue by girishkumar517** [webdriverio-boneyard/wdio-selenium-standalone-service#44]
C:\Framework>npx ntaf run wdio.local.conf.js
npx: installed 1 in 19.119s
Path must be a string. Received undefined
C:\Framework\node_modules\ntaf\bin\ntaf.js
A service failed in the 'onPrepare' hook
Error: Could not download https://download.microsoft.com/download/D/4/1/D417998A
-58EE-4EFE-A7CC-39EF9E020768/MicrosoftWebDriver.exe: Error: connect ETIMEDOUT 23
.54.115.197:443
    at Request.<anonymous> (C:\Framework\node_modules\selenium-standalone\lib\in
stall.js:386:12)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Framework\node_modules\request\request.js:845:
8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)

Continue...
ERROR: connect ECONNREFUSED 127.0.0.1:4444
chrome
    at new RuntimeError (C:\Framework\node_modules\webdriverio\build\lib\utils\E
rrorHandler.js:144:12)
    at Request._callback (C:\Framework\node_modules\webdriverio\build\lib\utils\
RequestHandler.js:327:43)
    at self.callback (C:\Framework\node_modules\webdriverio\node_modules\request
\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Framework\node_modules\webdriverio\node_module
s\request\request.js:878:8)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

0 steps (0 passed, 0 failed, 0 pending)

**Comment by christian-bromann** [comment]
Please report this error to the [selenium-standalone](https://github.com/vvo/selenium-standalone) package. Thanks!
