### ISSUE TITLE
ERROR: Cannot define class using reflection on wdio start

### ISSUE THREAD

**Issue by Xotabu4** [webdriverio-boneyard/wdio-selenium-standalone-service#47]
Getting exceptions:
```
> wdio

ERROR: Cannot define class using reflection
chrome
    at new RuntimeError (/Users/oleksandrkhotemskyi/Documents/GitHub/automated-testing-tool/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/Users/oleksandrkhotemskyi/Documents/GitHub/automated-testing-tool/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
    at Request.self.callback (/Users/oleksandrkhotemskyi/Documents/GitHub/automated-testing-tool/node_modules/webdriverio/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at Request.<anonymous> (/Users/oleksandrkhotemskyi/Documents/GitHub/automated-testing-tool/node_modules/webdriverio/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at IncomingMessage.<anonymous> (/Users/oleksandrkhotemskyi/Documents/GitHub/automated-testing-tool/node_modules/webdriverio/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:422:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)

0 steps (0 passed, 0 failed, 0 pending)

npm ERR! Test failed.  See above for more details.
```
I believe this might be because of too new java version:

```
java --version
java 10 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

Config:
```
exports.config = {
    specs: [
        './src/features/**/*.feature',
    ],
    capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',
    }],
    sync: true,
    logLevel: 'error',
    coloredLogs: true,
    reporters: ['cucumber'],
    baseUrl: 'http://www.google.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 5000,
    connectionRetryCount: 3,
    services: ['selenium-standalone'],
    framework: 'cucumber',
    cucumberOpts: {
        require: [
            './src/steps/hooks.js',
            './src/steps/given.js',
            './src/steps/when.js',
            './src/steps/then.js',
        ],
    },
    before: function before() {
        const chai = require('chai');
        global.expect = chai.expect;
        global.assert = chai.assert;
        global.should = chai.should();
    },
};

```

Dependencies:
```
  "dependencies": {
    "wdio-screenshot": "^0.6.0",
    "wdio-spec-reporter": "^0.1.3",
    "chai": "~4.1.2",
    "wdio-cucumber-framework": "2.0.1",
    "wdio-cucumber-reporter": "0.0.2",
    "wdio-selenium-standalone-service": "~0.0.10",
    "webdriverio": "4.12.0"
  }
```

**Comment by christian-bromann** [comment]
See https://github.com/Codeception/Codeception/issues/4657#issuecomment-348354476

**Comment by edi9999** [comment]
I have pushed this issue in the Selenium Google Group , but no response from them yet : https://groups.google.com/forum/#!searchin/selenium-users/java$2010%7Csort:date/selenium-users/h_lCnJTtEb8/yteuaONXBgAJ

**Comment by betweenbrain** [comment]
@edi9999 is it your opinion that Java 10 should work?

**Comment by edi9999** [comment]
Yes, I'm not a contributor to Selenium, but to me it is a bug that selenium does not work on newer versions of Java. (Java 10)

**Comment by joscha** [comment]
@christian-bromann any reason you closed this issue? Will JDK10 not be supported?

**Comment by christian-bromann** [comment]
> Will JDK10 not be supported?

I don't know but it is not a problem for this service as it only starts the java server and is not concerned about what runs in that java server. That being said, I doubt that they won't support JDK10.

**Comment by arturbek** [comment]
The issue is related to JDK10, please downgrade java to 8. This should fix your issue

**Comment by joscha** [comment]
@arturbek I understand that that fixes the issue, but staying on jdk8 is a temporary measure.
