### ISSUE TITLE
A service failed in the 'onPrepare' hook

### ISSUE THREAD

**Issue by IDIDIR** [webdriverio-boneyard/wdio-selenium-standalone-service#48]
the connection timeout is a floating error, but because of the attempt to install the browser drivers every time the test is started with this service, the tests quite often fail to start.
I understand that the error is not with the service. you can add a driver check before the test, which is available in selenium-standalone because at timeout, in addition to what I'm waiting for about thirty seconds, it still does not start. It does not start when there are already installed browser drivers.

`A service failed in the 'onPrepare' hook
Error: Could not request headers from https://selenium-release.storage.googleapis.com/3.7/IEDriverServer_Win32_3.7.0.zip: Error: connect ETIMEDOUT 74.125.205.128:443
    at Request.<anonymous> (C:\Users\node\Desktop\AT\TAS_RC\node_modules\selenium-standalone\lib\install.js:552:8)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\node\Desktop\AT\TAS_RC\node_modules\selenium-standalone\node_modules\request\request.js:845:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)

Continue...`

**Comment by christian-bromann** [comment]
> Error: Could not request headers from selenium-release.storage.googleapis.com/3.7/IEDriverServer_Win32_3.7.0.zip: Error: connect ETIMEDOUT 74.125.205.128:443

Seems like a connection issue of your machine to the selenium server. This might be temporary.
