### ISSUE TITLE
it won't download the selenium standalone server correctly if the second minor is double digits

### ISSUE THREAD

**Issue by caoxu2000** [webdriverio-boneyard/wdio-selenium-standalone-service#59]
The latest selenium-standalone server version is 3.141.59. So the second minor version is .59. That caused the issue when it was downloading Selenium server since the path is not correct:

A service failed in the 'onPrepare' hook
Error: Could not download https://selenium-release.storage.googleapis.com/3.1419/selenium-server-standalone-3.141.59.jar
    at Request.<anonymous> (/Users/xcao/Desktop/qa-ui-functional/node_modules/selenium-standalone/lib/install.js:373:21)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/Users/xcao/Desktop/qa-ui-functional/node_modules/request/request.js:1066:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)

Continue...
ERROR: connect ECONNREFUSED 127.0.0.1:4444

Notice the correct download file path is https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar

in wdio.conf.js I have this seleniumArgs and installArgs:
exports.config = {
    seleniumInstallArgs: { version: '3.141.0', drivers: { chrome: { version: '2.45' } } },
    seleniumArgs: { version: '3.141.0', drivers: { chrome: { version: '2.45' } } },
...
}

**Comment by jackson-sandland** [comment]
Does `@wdio/selenium-standalone-service` download `selenium-standalone` on it's own?
Or do we need to also have the `selenium-standalone` node module installed independently?

**Example dependencies section of package.json**:
```
  "dependencies": {
    "@wdio/sauce-service": "^5.3.2",
    "@wdio/selenium-standalone-service": "^5.2.2",
    "@wdio/spec-reporter": "^5.2.3",
    "@wdio/sync": "^5.3.2",
    "chai": "^4.2.0",
    "webdriverio": "^5.3.5"
  },
  "devDependencies": {
    "@wdio/cli": "^5.3.5",
    "@wdio/local-runner": "^5.3.5",
    "@wdio/mocha-framework": "^5.3.2",
    "chai-webdriverio": "^1.0.0",
    "chromedriver": "^74.0.0",
    "geckodriver": "^1.16.2",
    "selenium-standalone": "^6.15.4"
  }
}
```
