### ISSUE TITLE
ERROR: Couldn't initialise service "selenium-standalone".

### ISSUE THREAD

**Issue by danielleballas** [webdriverio-boneyard/wdio-selenium-standalone-service#63]
Hi all
I am using selenium-standalone as service ,
my conf looks like:
capabilities: [{
    maxInstances: 5,
    browserName: 'chrome',
    'chromeOptions': {
            args: ['--no-sandbox', '--test-type=browser'],
            prefs: {
                download: {
                    'prompt_for_download': false,
                    'directory_upgrade': true,
                    'default_directory': './tmp/'
                }
            }
    }
  }],
  services: ['selenium-standalone'],
  port: '4444',
  path: '/',
  sync: true,

my package.json:
"dependencies": {
    "@wdio/selenium-standalone-service": "^5.11.2",
    "chromedriver": "^2.45.0",
    "wdio-chromedriver-service": "^5.0.1",
    "wdio-jasmine-framework": "^0.3.8",
    "wdio-junit-reporter": "^0.4.4",
    "wdio-spec-reporter": "^0.1.5",
    "webdriverio": "4.13.2"
  }
and getting this error:
ERROR: Couldn't initialise service "selenium-standalone".
Error: Cannot find module 'wdio-selenium-standalone-service'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Runner.initialiseServices (/usr/local/lib/node_modules/webdriverio/build/lib/runner.js:689:35)
    at Runner._callee$ (/usr/local/lib/node_modules/webdriverio/build/lib/runner.js:94:38)
    at tryCatch (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)

**Comment by christian-bromann** [comment]
You are using v5 of the service while WebdriverIO is on v4. These are not compatible with each other. I recommend upgrading to v5.

**Comment by danielleballas** [comment]
@christian-bromann can I downgrade wdio-selenium-standalone-service to v4? 
and also what are the differences between  wdio-selenium-standalone-service to @wdio/selenium-standalone-service?

**Comment by christian-bromann** [comment]
> can I downgrade wdio-selenium-standalone-service to v4?

Sure but we recommend to use v5. We don't maintain v4 anymore.

> what are the differences between wdio-selenium-standalone-service to @wdio/selenium-standalone-service?

First is v4 last is v5.

**Comment by danielleballas** [comment]
@christian-bromann when I use wdio-selenium-standalone-service ("wdio-selenium-standalone-service": "0.0.12") for v4 I still get the same error.

**Comment by christian-bromann** [comment]
Hard to give advice without knowing the error. Generally I advise to upgrade to v5!

**Comment by danielleballas** [comment]
@christian-bromann Hi again,
I upgrade to v5 but still getting error:
**package.json:** 
```
"dependencies": {
    "chromedriver": "^2.45.0",
    "webdriverio": "^5.11.2"
  },
  "devDependencies": {
    "@wdio/cli": "^5.11.2",
    "@wdio/dot-reporter": "^5.11.0",
    "@wdio/jasmine-framework": "^5.11.0",
    "@wdio/junit-reporter": "^5.11.0",
    "@wdio/selenium-standalone-service": "^5.11.2",
    "@wdio/spec-reporter": "^5.11.0"
  }
```
**the error:** 
```
ERROR: Couldn't initialise service "selenium-standalone".
Error: Cannot find module 'wdio-selenium-standalone-service'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Runner.initialiseServices (/usr/local/lib/node_modules/webdriverio/build/lib/runner.js:689:35)
    at Runner._callee$ (/usr/local/lib/node_modules/webdriverio/build/lib/runner.js:94:38)
    at tryCatch (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)

```

can you please help?
